<a href="https://colab.research.google.com/github/rohillatanisha676-del/Machine-learning/blob/main/LAB_01_Using_code_of_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df=pd.read_csv('insurance.csv')

In [2]:
df

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [3]:
df.shape #TO check rows and columns

(1338, 7)

In [4]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [5]:
df.head(10)

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86
5   31  female  25.7         0     no  southeast   3756.62
6   46  female  33.4         1     no  southeast   8240.59
7   37  female  27.7         3     no  northwest   7281.51
8   37    male  29.8         2     no  northeast   6406.41
9   60  female  25.8         0     no  northwest  28923.14

In [6]:
df.head(2999)

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [7]:
df.tail()

      age     sex   bmi  children smoker     region  expenses
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

In [8]:
df.tail(45)

      age     sex   bmi  children smoker     region  expenses
1293   46    male  25.7         3     no  northwest   9301.89
1294   58    male  25.2         0     no  northeast  11931.13
1295   20    male  22.0         1     no  southwest   1964.78
1296   18    male  26.1         0     no  northeast   1708.93
1297   28  female  26.5         2     no  southeast   4340.44
1298   33    male  27.5         2     no  northwest   5261.47
1299   19  female  25.7         1     no  northwest   2710.83
1300   45    male  30.4         0    yes  southeast  62592.87
1301   62    male  30.9         3    yes  northwest  46718.16
1302   25  female  20.8         1     no  southwest   3208.79
1303   43    male  27.8         0    yes  southwest  37829.72
1304   42    male  24.6         2    yes  northeast  21259.38
1305   24  female  27.7         0     no  southeast   2464.62
1306   29  female  21.9         0    yes  northeast  16115.30
1307   32    male  28.1         4    yes  northwest  21472.48
1308   25  female  30.2         0    yes  southwest  33900.65
1309   41    male  32.2         2     no  southwest   6875.96
1310   42    male  26.3         1     no  northwest   6940.91
1311   33  female  26.7         0     no  northwest   4571.41
1312   34    male  42.9         1     no  southwest   4536.26
1313   19  female  34.7         2    yes  southwest  36397.58
1314   30  female  23.7         3    yes  northwest  18765.88
1315   18    male  28.3         1     no  northeast  11272.33
1316   19  female  20.6         0     no  southwest   1731.68
1317   18    male  53.1         0     no  southeast   1163.46
1318   35    male  39.7         4     no  northeast  19496.72
1319   39  female  26.3         2     no  northwest   7201.70
1320   31    male  31.1         3     no  northwest   5425.02
1321   62    male  26.7         0    yes  northeast  28101.33
1322   62    male  38.8         0     no  southeast  12981.35
1323   42  female  40.4         2    yes  southeast  43896.38
1324   31    male  25.9         1     no  northwest   4239.89
1325   61    male  33.5         0     no  northeast  13143.34
1326   42  female  32.9         0     no  northeast   7050.02
1327   51    male  30.0         1     no  southeast   9377.90
1328   23  female  24.2         2     no  northeast  22395.74
1329   52    male  38.6         2     no  southwest  10325.21
1330   57  female  25.7         2     no  southeast  12629.17
1331   23  female  33.4         0     no  southwest  10795.94
1332   52  female  44.7         3     no  southwest  11411.69
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

In [9]:
df.describe

<bound method NDFrame.describe of       age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]>

In [10]:
df.describe(

) # It has 7 columns and it showed only 4 and skiped the rest

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [11]:
#data cleaning
#check null values
#check missing values